beer_warehaus/urls.py
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('producers/', include('producers.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_cart, name='cart'),
    path('add/<item_id>/', views.add_to_cart, name='add_to_cart'),
    path('adjust/<item_id>/', views.adjust_cart, name='adjust_cart'),
    path('remove/<item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('manage_slides/', views.manage_slides, name='manage_slides'),
    path('manage_slides/add/', views.add_slide, name='add_slide'),
    path('manage_slides/edit/<int:slide_id>/', views.edit_slide, name='edit_slide'),
    path('manage_slides/delete/<int:slide_id>/', views.delete_slide, name='delete_slide'),
]

home/models.py
from django.db import models
# from PIL import Image
# from io import BytesIO
# from django.core.files.uploadedfile import InMemoryUploadedFile
# import sys


class Slide(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='slides', null=True, blank=True, default='/slides/generic.jpg')
    cta_txt = models.CharField(max_length=30)
    cta_link = models.CharField(max_length=500)

    def __str__(self):
        return self.title

    # def save(self):
    #     # Opening the uploaded image
    #     image = Image.open(self.image)

    #     output = BytesIO()

    #     # Resize/modify the image
    #     image = image.resize((1600, 900))

    #     # after modifications, save it to the output
    #     image.save(output, format='JPEG', quality=100)
    #     output.seek(0)

    #     # change the imagefield value to be the newley modifed image value
    #     self.img = InMemoryUploadedFile(output, 'ImageField', "%s.jpg" %self.img.name.split('.')[0], 'image/jpeg', sys.getsizeof(output), None)

    #     super(Slide, self).save()

home/forms.py
from django import forms
from .models import Slide

from products.widgets import CustomClearableFileInput


class SlideForm(forms.ModelForm):

    class Meta:
        model = Slide
        fields = '__all__'

    image = forms.ImageField(label='Image', required=False, widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'dark-border'

home/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .models import Slide
from .forms import SlideForm
from products.models import Product


def index(request):

    slides = Slide.objects.all()
    products = Product.objects.filter(new_product=True)

    context = {
        'slides': slides,
        'products': products,
    }

    return render(request, 'home/index.html', context)


@login_required
def manage_slides(request):
    if not request.user.is_superuser:
        # If user is not an admin, redirect to home page
        messages.error(request, "Only store owners can access this page.")
        return redirect(reverse('home'))

    slides = Slide.objects.all()

    context = {
        'slides': slides,
    }

    return render(request, 'home/manage_slides.html', context)


@login_required
def edit_slide(request, slide_id):
    """
    # Edit an existing slide on the homepage
    """
    if not request.user.is_superuser:
        # If user is not an admin, redirect to home page
        messages.error(request, "Only store owners can access this page.")
        return redirect(reverse('home'))

    slide = get_object_or_404(Slide, pk=slide_id)

    if request.method == 'POST':
        form = SlideForm(request.POST, request.FILES, instance=slide)

        # Ensure form is valid before updating the database
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated slide information.')
            return redirect(reverse('manage_slides'))
        else:
            messages.error(request, 'There was an error updating this slide. \
                Please ensure the form is valid.')

    else:
        form = SlideForm(instance=slide)
        messages.info(request, f'You are editing the slide titled "{slide.title}".')
    context = {
            'form': form,
            'slide': slide,
        }
    template = 'home/edit_slide.html'

    return render(request, template, context)


@login_required
def delete_slide(request, slide_id):
    """
    # Remove a slide from the homepage carousel
    """
    if not request.user.is_superuser:
        # If user is not an admin, redirect to home page
        messages.error(request, "Only store owners can access this page.")
        return redirect(reverse('home'))

    slide = get_object_or_404(Slide, pk=slide_id)
    slide.delete()
    messages.success(request, 'Successfully removed slide from the homepage.')
    return redirect(reverse('home'))


@login_required
def add_slide(request):
    """
    # Handles adding a new slide to the homepage
    """
    if not request.user.is_superuser:
        # If user is not an admin, redirect to home page
        messages.error(request, "Only store owners can access this page.")
        return redirect(reverse('home'))

    if request.POST:
        """
        # Form submission to add new producer
        """
        form = SlideForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully added new slide to homepage.')
            return redirect(reverse('manage_slides'))

        else:
            messages.error(request, 'There was an error saving the slide. Please ensure the form is valid.')

    else:
        form = SlideForm
        context = {
                'form': form,
            }

    template = 'home/add_slide.html'

    return render(request, template, context)

home/templates/home/add_slide.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-10 offset-1 product-container">
            <div class="row">
                <div class="col">
                    <h2 class="h2-page-title">Add New Slide</h2>
                </div>
            </div>

            <div class="row">
                <div class="col-12 col-md-6 order-2 order-md-1">
                    <form action=" {% url 'add_slide'%}" method="POST" id="add-slide-form" class="form mb-2"
                        enctype="multipart/form-data">
                        <!-- The following form adds a new slide to the homepage -->
                        {% csrf_token %}
                        {% for field in form %}
                        {% if field.name != 'image' %}
                        {{ field | as_crispy_field }}
                        {% else %}
                        {{ field }}
                        {% endif %}
                        {% endfor %}
                        <a href="{% url 'manage_slides' %}" class="btn btn-outline-gold">
                            <i class="fas fa-angle-left"></i> Back
                        </a>
                        <button class="btn btn-gold" type="submit">
                            Add Slide <i class="fas fa-beer ml-1"></i>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock%}

{% block postloadjs %}
{{ block.super }}
<script>
    $('#new-image').change(function () {
        let file = $('#new-image')[0].files[0];
        $('#filename').text(`Image will be set to ${file.name}`);
    })

    // Change text of image button
    $(document).ready(function () {
        if ($('#widget-image').length == 0) {
            $('#new-image-text').text('Choose Image');
        }
    })
</script>
{% endblock %}

home/templates/home/edit_slide.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-10 offset-1 product-container">
            <div class="row">
                <div class="col">
                    <h2 class="h2-page-title">Edit Slide</h2>
                </div>
            </div>

            <div class="row">
                <div class="col-12 col-md-6 order-2 order-md-1">
                    <form action=" {% url 'edit_slide' slide.id %}" method="POST" id="edit-slide-form" class="form mb-2"
                        enctype="multipart/form-data">
                        <!-- The following form edits the currently selected slide -->
                        {% csrf_token %}
                        {% for field in form %}
                        {% if field.name != 'image' %}
                        {{ field | as_crispy_field }}
                        {% else %}
                        <p>Current Image:</p>
                        <a href="{{ slide.image.url}}">
                            <img class="w-50" id="widget-image" src="{{ slide.image.url }}" alt="{{ slide.name }}">
                        </a>
                        {{ field }}
                        {% endif %}
                        {% endfor %}
                        <a href="{% url 'manage_slides' %}" class="btn btn-outline-gold">
                            <i class="fas fa-angle-left"></i> Back
                        </a>
                        <button class="btn btn-gold" type="submit">
                            Update Slide <i class="fas fa-beer ml-1"></i>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock%}

<!-- The following ensures the functionality of the image selector -->
{% block postloadjs %}
{{ block.super }}
<script>
    $('#id_image').change(function () {
        let file = $('#id_image')[0].files[0];
        $('#filename').text(`Image will be set to ${file.name}`);
    })
</script>
{% endblock %}

home/templates/home/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- Homepage slideshow -->

<div class="container-fluid w-100 p-0">
    <div id="home-carousel" class="carousel slide carousel-fade" data-interval="false" data-ride="carousel"
        data-touch="true">
        <div class="carousel-inner w-100">

            {% for slide in slides %}
            <div class="carousel-item custom-carousel-item {% if forloop.first %}active{% endif %}">
                <img src="{{ slide.image.url }}" class="slide-img" alt="{{ slide.title }}">
                <div class="carousel-caption slide-caption">
                    <h2 class="slideshow-title">{{ slide.title }}</h2>
                    <p class="w-50 ml-auto d-none d-sm-block">{{ slide.description }}</p>
                    <a href="{{ slide.cta_link }}" class="btn btn-gold">{{ slide.cta_txt }}</a>
                </div>
            </div>
            {% endfor %}

        </div>
        <a class="carousel-control-prev carousel-control" href="#home-carousel" role="button" data-slide="prev">
            <span aria-hidden="true"><i class="fas fa-caret-left fa-lg"></i></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next carousel-control" href="#home-carousel" role="button" data-slide="next">
            <span aria-hidden="true"><i class="fas fa-caret-right fa-lg"></i></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

<!-- Newest Releases -->
<div class="container-fluid mb-3">
    <div class="row">
        <div class="col-10 offset-1 product-container">
            <div class="row">
                <div class="col p-0">
                    <h2 class="h2-page-title" id="new-products">New Products</h2>
                </div>
            </div>
            <div class="row">
                <div class="row mt-3">
                    {% for product in products %}
                    <div class="col-sm-6 col-lg-4 col-xl-3 mb-3">
                        <div class="card h-100 listing-card overflow-hidden">
                            {% if product.image_url %}
                            <a href="{% url 'product_detail' product.id %}" {% if product.new_product %}
                                class="new-product" {% endif %}>
                                <img class="card-img-top img-fluid custom-card-img" src="{{ product.image_url }}"
                                    alt="{{ product.name }}">
                            </a>
                            {% elif product.image %}
                            <a href="{% url 'product_detail' product.id %}" {% if product.new_product %}
                                class="new-product" {% endif %}>
                                <img class="card-img-top img-fluid custom-card-img" src="{{ product.image.url }}"
                                    alt="{{ product.name }}">
                            </a>
                            {% else %}
                            <a href="{% url 'product_detail' product.id %}{% if product.new_product %} class="
                                new-product" {% endif %}">
                                <img class="card-img-top img-fluid custom-card-img" src="{{ MEDIA_URL }}no-image.png"
                                    alt="{{ product.name }}">
                            </a>
                            {% endif %}
                            <div class="card-body pb-0">
                                <h3 class="mb-0 text-center h4">{{ product.name }}</h3>
                                <p class="card-text mb-2 text-center">
                                    <a href="{% url 'producer_detail' product.producer.id %}">
                                        {{ product.producer }}
                                    </a>
                                </p>
                                <p class="text-center font-weight-bold">
                                    {% if product.packaging == 'keg' %}
                                    {{ product.volume }} keg
                                    {% else %}
                                    {{ product.volume }} x {{ product.units_per_order }} {{ product.packaging}}s
                                    {% endif %}
                                </p>
                                <p class="mb-0">
                                    <strong>Style:</strong> <a href="{% url 'products'%}?style={{ product.style }}">
                                        {{ product.style.friendly_name }}
                                    </a>
                                </p>
                                <p class="m-0"><strong>Abv: </strong>{{ product.abv }}%</p>
                                {% if product.rating %}
                                <p class="m-0"><i class="fab fa-untappd"></i> Rating: {{ product.rating }} / 5</p>
                                {% else %}
                                <p class="m-0">No Rating</p>
                                {% endif %}

                            </div>
                            <div class="card-footer pt-0 border-0 bg-white">
                                {% if product.packaging == 'keg' %}
                                <p class="text-muted mb-0 mt-2">Price:</p>
                                {% else %}
                                <p class="text-muted mb-0 mt-2">Price per unit:</p>
                                {% endif %}
                                <p class="lead mb-0 font-weight-bold text-right">
                                    NOK {{ product.price }}
                                </p>

                                <!-- Product Management for shop admin -->
                                {% if request.user.is_superuser %}
                                <div class="text-right">
                                    <small>
                                        <a href="{% url 'edit_product' product.id %}">Edit</a> |
                                        <a class="text-danger" href="#delete-product-{{ product.id }}"
                                            data-target="#delete-product-{{ product.id }}"
                                            data-toggle="modal">Delete</a>
                                    </small>
                                </div>

                                <!-- Modal window for product deletion -->
                                <div class="modal" id="delete-product-{{ product.id }}" tabindex="-1" role="dialog"
                                    aria-labelledby="delete-{{ product.id }}-title" aria-hidden="true">
                                    <div class="modal-dialog modal-dialog-centered" role="document">
                                        <div class="modal-content rounded-0">
                                            <div class="modal-header">
                                                <h5 class="modal-title font-weight-bold text-uppercase"
                                                    id="delete-{{ product.id }}-title">
                                                    <i class="fas fa-exclamation-triangle text-danger"></i> You are
                                                    about to delete a
                                                    product!</h5>
                                                <button type="button" class="close" data-dismiss="modal"
                                                    aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <p>"{{ product.name }}" by {{ product.producer }} will be removed from
                                                    the
                                                    store. This action
                                                    cannot be reversed.</p>
                                                <p class="font-weight-bold">Are you sure you want to do this?</p>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button"
                                                    class="btn btn-secondary btn-outline-gold rounded-0"
                                                    data-dismiss="modal">cancel</button>
                                                <a href="{% url 'delete_product' product.id %}"
                                                    class="btn btn-primary btn-danger-custom rounded-0 text-uppercase"><i
                                                        class="fas fa-trash-alt"></i> delete</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="row text-center mb-2">
                <a href="{% url 'products' %}" class="btn btn-gold  ml-auto mr-auto">View all products</a>
            </div>
        </div>
    </div>
</div>


{% endblock%}

home/templates/home/manage_slides.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-10 offset-1 product-container">
            <div class="row mb-2">
                <div class="col">
                    <h2 class="h2-page-title d-inline-block">
                        Slideshow Management
                    </h2>
                    <a href="{% url 'add_slide' %}" class="ml-3 btn btn-gold">
                        <i class="fas fa-plus-circle mr-2"></i> New slide
                    </a>
                </div>
            </div>
            <!-- Homepage slides -->
            {% for slide in slides %}
            <div class="row">
                <div class="col-3">
                    <img src="{{ slide.image.url }}" class="img-fluid" alt="{{ slide.title }}">
                </div>
                <div class="col-9">
                    <p class="h5 mb-1">{{ slide.title }}</p>
                    <p class="mb-1">{{ slide.description }}</p>
                    <div class="row mt-2">
                        <div class="col">
                            <a class="btn btn-outline-gold" href="{% url 'edit_slide' slide.id %}">
                                <i class="fas fa-pencil-alt mr-2"></i> Edit
                            </a>
                            <a class="btn btn-danger-custom" href="#delete-slide-{{ slide.id }}"
                                data-target="#delete-slide-{{ slide.id }}" data-toggle="modal">
                                <i class="fas fa-trash-alt mr-2"></i> Delete
                            </a>
                        </div>
                    </div>


                </div>

                <!-- Modal window for slide deletion -->
                <div class="modal" id="delete-slide-{{ slide.id }}" tabindex="-1" role="dialog"
                    aria-labelledby="delete-{{ slide.id }}-title" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered text-left" role="document">
                        <div class="modal-content rounded-0">
                            <div class="modal-header">
                                <h5 class="modal-title font-weight-bold text-uppercase"
                                    id="delete-{{ slide.id }}-title">
                                    <i class="fas fa-exclamation-triangle text-danger"></i> You are about to delete
                                    a slide!
                                </h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <p>The slide titled "{{ slide.title }}" will be removed from the home page.
                                    This action cannot be reversed.</p>
                                <p class="font-weight-bold">Are you sure you want to do this?</p>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary btn-outline-gold rounded-0"
                                    data-dismiss="modal">cancel</button>
                                <a href="{% url 'delete_slide' slide.id %}"
                                    class="btn btn-primary btn-danger-custom rounded-0 text-uppercase"><i
                                        class="fas fa-trash-alt"></i> delete</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <hr>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock%}

{% block postloadjs %}
{{ block.super }}
{% endblock %}